### ISSUE TITLE
[Question] Where can i find the DC removal Tool?

### ISSUE THREAD

**Issue by kC0pter** [mohabouje/eDSP#17]
I cannot find the DC removal Tool in the code.
Is it implemented and if yes where can i find it?

PS: Nice library. Really easy to use and and to setup.

**Comment by mohabouje** [comment]
Thanks, I hope to get some free time soon to keep working on this.

Probably, the tool was removed in old commits, you can create a simple DC-filter by using one of the provided filters:
* RMS moving window
* Moving average
* Or use a simple biquad filter

I think that eDSP should provide the blocks to build stuff on top. In this case, this link can help you:  https://www.dsprelated.com/freebooks/filters/DC_Blocker.html

You can also build a linear-phase dc: https://www.dsprelated.com/showarticle/58.php

**Comment by kC0pter** [comment]
Thanks for the reply.

Since i am doing postprocessing of my measurements i just calculated the mean and subtracted it.
But thanks for the reference.
